routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('items.jumbotron');
});

Route::get('/test-dompdf', function() {
    $pdf = App::make('dompdf.wrapper');
    $pdf->loadHTML('<h1>Test</h1>');
    return $pdf->stream();
});

Auth::routes();
Route::get('/test-dompdf-2/{article}', 'pdfcontroller@test');

Route::get('/test-excel', 'ArticleController@export');


Route::get('/home', 'HomeController@index')->name('home');
//Route::resource('article', 'ArticleController');
Route::resource('profile', 'profileController');

Route::get('/article', 'ArticleController@index' )->name('article.index');
Route::get('/article/create', 'ArticleController@create')->name('article.create');
Route::post('/article', 'ArticleController@store')->name('article.store');
Route::get('/article/{article}', 'ArticleController@show')->name('article.show');
Route::get('/article/{article}/edit', 'ArticleController@edit')->name('article.edit');
Route::put('/article/{article}', 'ArticleController@update')->name('article.update');
Route::delete('/article/{article}', 'ArticleController@destroy')->name('article.destroy');

Route::put('/comment/{article}', 'CommentController@store')->name('comment.store');

resources/views/items/Jumbotron.blade.php
@extends('welcome')

@section('content')
<header>
    <div class="jumbotron atas">
        <h1 class="display-4">Welcome to <span>TECHNO BLOG</span></h1>
        <p class="lead judul" style="color:white">This is a simple Blog, place of Information <a href="#" class="active">Teknologi</a></p>
        <div class="garis"></div>
        <p class="lead tombol">
            <a class="btn btn-lg" href="/article" role="button">Go To List</a>
        </p>
    </div>
    <div class="container topic">
        <div class="row">
            <div class="col-sm-4">
                <span class="text"> NEW ARTIKEL</span>
                <br>
                <div class="row">
                    <div class="col-sm-3">
                        <div class="text-center picture">
                            <img src="{{asset('/material/bigdata1.jpg')}}" class="rounded" alt="...">
                        </div>
                    </div>
                    <div class="col-sm-1 kanan">
                        <span style="font-size: 50%; letter-spacing: 2px;">DATABASE</span> 
                        <a href="#">Bigdata</a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-3">
                        <div class="text-center picture">
                            <img src="{{asset('/material/js.jpg')}}" class="rounded" alt="...">
                        </div>
                    </div>
                    <div class="col-sm-1 kanan">
                        <span style="font-size: 50%; letter-spacing: 2px; line-height: -40px;">WEB</span>
                       <a href="#">JavaScript</a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-3">
                        <div class="text-center picture">
                            <img src="{{asset('/material/ml.jpg')}}" class="rounded" alt="...">
                        </div>
                    </div>
                    <div class="col-sm-1 kanan">
                        <span style="font-size: 50%; letter-spacing: 2px;">MACHINE</span>
                       <a href="#">Machine Learning</a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-3">
                        <div class="text-center picture">
                            <img src="{{asset('/material/dv.jpg')}}" class="rounded" alt="...">
                        </div>
                    </div>
                    <div class="col-sm-1 kanan">
                        <span style="font-size: 50%; letter-spacing: 2px;">DATABASE</span>
                       <a href="#">Data Visualitation</a>
                    </div>
                </div>
                <div class="row see">
                    <div class="col-sm-4">
                        <a href="#" style="color: white; font-size: 80%; border-bottom: 2px solid rgb(255, 238, 0);">
                            SEE MORE
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-sm-8 jumbo z-0">
                <div class="jumbotron" style="position: relative;">
                    <div class="container">
                      <h1 class="display-4 text1">Artificial Intelligence</h1>
                      <a href="#" class="text1 mt-2" style=" letter-spacing: 5px; margin-left:-20px; margin-top:-10px;font-size:60%; font-weight:bold; text-decoration:none; color:white;">
                        <img src="{{asset('/material/justified.png')}}" style="width: 15px; height:20px;" alt="">
                      READ</a>
                    </div>
                  </div>
            </div>
        </div>
    </div>
</header>

    {{-- <section style="background-color: white;" class="mt-20">
        <h2>New Artikel</h2>
        <ul>
            <li>BIG DATA</li>
            <li>JAVASCRIPT</li>
            <li>MACHINE LEARNING</li>
            <li>DATA VISUALITATION</li>
    </ul>

</section> --}}

@endsection

resources/views/items/SuccessEdit.blade.php
@extends('welcome')

@section('content')
<div style="margin-top:100px"></div>
<div class="container-fluid">
                            @if (Route::has('login'))
                                    @auth
                                    <div class="card-body">
                                                        <div class="alert alert-success">
                                                           <h1>Success Update Profil</h1>
                                                           <a href="/profile/{{Auth::user()->id}}" class="btn btn-primary">BACK</a>
                                                        </div>   
                                    </div>
                                    
                                    @else
                                    <h1>Coba lagi</h1>
                                    @endauth
                            @endif
     
</div>


@endsection

resources/views/items/SuccessEdit2.blade.php
@extends('welcome')

@section('content')
<div style="margin-top:100px"></div>
<div class="container-fluid">
                            @if (Route::has('login'))
                                    @auth
                                    <div class="card-body">
                                                        <div class="alert alert-success">
                                                           <h1>Success Update Profil</h1>
                                                           <a href="/article" class="btn btn-primary">BACK</a>
                                                        </div>   
                                    </div>
                                    
                                    @else
                                    <h1>Coba lagi</h1>
                                    @endauth
                            @endif
     
</div>


@endsection

resources/views/items/create.blade.php
@extends('welcome')

@section('content')

<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title">Create Article</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form role="form" action="{{route('article.store')}}" method="POST">
        @csrf
        <div class="card-body">
            <div class="form-group">
                <label for="title">Title</label>
                <input type="text" class="form-control" id="title" name ="title" value="{{old('title', '')}}" placeholder="title">
            </div>
            <div class="form-group">
                <label for="detail_article">detail_article</label>
                <input type="text" class="form-control" id="detail_article" name="detail_article" value="{{old('detail_article', '')}}" placeholder="detail_article">
            </div>
            <!-- <div class="form-group">
                <label for="user_id">user_id</label>
                <input type="text" class="form-control" id="user_id" name="user_id" value="{{old('user_id', '')}}" placeholder="user_id">
            </div> -->
        </div>
                <!-- /.card-body -->
        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>


@endsection

resources/views/items/createProfile.blade.php
@extends('welcome')

@section('content')

<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title">Create Profile</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form role="form" action="{{route('profile.store')}}" method="POST">
        @csrf
        <div class="card-body">
            <div class="form-group">
                <label for="name">name</label>
                <input type="text" class="form-control" id="name" name ="name" value="{{old('name', '')}}" placeholder="name">
            </div>
            <div class="form-group">
                <label for="email">email mu adalah {{Auth::user()->email}}</label>
                <input type="text" class="form-control" id="email" name="email" value="{{old('email', '')}}" placeholder="email">
            </div>
            <div class="form-group">
                <label for="photo">photo</label>
                <input type="text" class="form-control" id="photo" name="photo" value="{{old('photo', '')}}" placeholder="photo">
            </div>
            <div class="form-group">
                <label for="bio">bio</label>
                <input type="text" class="form-control" id="bio" name="bio" value="{{old('bio', '')}}" placeholder="bio">
            </div>
            <div class="form-group">
                <label for="user_id">user_id mu adalah {{Auth::user()->id}}</label>
                <input type="text" class="form-control" id="user_id" name="user_id" value="{{old('user_id', '')}}" placeholder="user_id">
            </div>        
        </div>
                <!-- /.card-body -->
        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>

@endsection

resources/views/items/dataTabel.blade.php
@extends('welcome')

@section('content')
<div style="margin-top: 85px;"></div>
<div class="card">
      <div class="card-header">
        <h2 class="card-title"><strong>List Article</strong></h2>
      </div>
      <!-- /.card-header -->
      <div class="card-body">
      <a class="btn btn-primary mb-2" href="{{ route('article.create')}}">Create New Article</a>
        <table id="example1" class="table table-bordered table-striped">
          <thead>
            <tr>
              <th>Title</th>
              <th>Detail Article</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
          @foreach($article as $key => $data)
                <tr>
                    <td>{{$data->title}}</td>
                    <td>{{$data->detail_article}}</td>
                    <td>
                      <div style="display: flex;">
                      <a class="btn btn-sm btn-outline-success ml-2" href="{{ route('article.show', ['article'=> $data->id])}}">Show</a>
                      <a class="btn btn-sm btn-outline-primary ml-2" href="{{ route('article.edit', ['article'=> $data->id])}}">Edit</a>
                      <form action="{{ route('article.destroy', ['article'=> $data->id])}}" method="post">
                        @csrf 
                        @method('DELETE')
                        <input type="submit" value="delete" class="btn btn-sm btn-outline-danger ml-2">
                      </form>
                      <div>
                    </td>
                </tr>
          @endforeach
          </tbody>
        </table>
      </div>
    </div>
@endsection

@push('scripts')
  <script src="{{asset('/plugins/datatables/jquery.dataTables.min.js')}}"></script>
  <script src="{{asset('/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js')}}"></script>
  <script src="{{asset('/plugins/datatables-responsive/js/dataTables.responsive.min.js')}}"></script>
  <script src="{{asset('/plugins/datatables-responsive/js/responsive.bootstrap4.min.js')}}"></script>
  <!-- AdminLTE App -->
  <script src="{{asset('/dist/js/adminlte.min.js')}}"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="{{asset('/dist/js/demo.js')}}"></script>
  <!-- page script -->
  <script>
    $(function () {
      $("#example1").DataTable({
        "responsive": true,
        "autoWidth": false,
      });
    });
  </script>
@endpush

resources/views/items/edit.blade.php
@extends('welcome')

@section('content')

<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title">Edit Article</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form role="form" action="{{route('article.update',['article'=>$article->id])}}" method="post">
        @csrf
        @method('PUT')
        <div class="card-body">
            <div class="form-group">
                <label for="title">Title</label>
                <input type="text" class="form-control" id="title" name ="title" value="{{old('title', $article->title)}}" placeholder="title">
            </div>
            <div class="form-group">
                <label for="article">Article</label>
                <input type="text" class="form-control" id="article" name="article" value="{{old('article', $article->detail_article)}}" placeholder="article">
            </div>        
        </div>
                <!-- /.card-body -->
        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>

@endsection

resources/views/items/editProfile.blade.php
@extends('welcome')

@section('content')
<!-- general form elements -->
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Edit Pertanyaan</h3>
              </div>
              <!-- /.card-header -->
              <!-- form start -->
              <form role="form" action="{{route('profile.update',['profile'=>$profile->id])}}" method="POST">
                @csrf
                @method('PUT')
                <div class="card-body">
                  <div class="form-group">
                    <label for="name">name</label>
                    <input type="text" class="form-control" id="name" name="name" value="{{old('name',$profile->name)}}" placeholder="name">
                    @error('name')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                  </div>
                  <div class="form-group">
                    <label for="email">email</label>
                    <input type="text" class="form-control" id="email" name="email" value="{{old('email',$profile->email)}}" placeholder="email">
                    @error('email')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                  </div>
                  <div class="form-group">
                    <label for="bio">bio</label>
                    <input type="text" class="form-control" id="bio" name="bio" value="{{old('bio',$profile->bio)}}" placeholder="id">
                    @error('bio')
                        <div class="alert alert-danger">{{ $message }}</div>
                    @enderror
                  </div>
                  <!-- <div class="form-group">
                    <label for="jawaban_id">Jawaban_id</label>
                    <input type="text" class="form-control" id="jawaban_id" name="jawaban_id" placeholder="id">
                  </div>
                </div> -->
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Update</button>
                </div>
              </form>
            </div>
@endsection

resources/views/items/profil.blade.php
@extends('welcome')

@section('content')
<div style="margin-top:100px"></div>

<div class="container">
<div class="card" style="width:50%;margin-left:25%">
  <center><img src="/material/photo.png" style="width:100px;height:100px;margin:10px" alt="photo" class="card-img-top"></center>
  <div class="card-body">
    <center><h4 class="card-title">PROFILE</h4></center>
    <ul class="list-group list-group-horizontal-xl">
      <li class="list-group-item" style="width:20%">Name
      <li class="list-group-item" style="width:80%">{{$profile->name}}</li>
    </ul>
    <ul class="list-group list-group-horizontal-xl">
      <li class="list-group-item" style="width:20%">Email
      <li class="list-group-item" style="width:80%">{{$profile->email}}</li>
    </ul>
    <ul class="list-group list-group-horizontal-xl">
      <li class="list-group-item" style="width:20%">Bio</li>
      <li class="list-group-item" style="width:80%">{{$profile->bio}}</li>
    </ul>
    <center>
    <div style="margin-top:20px">
      <a href="/profile/{{$profile->id}}/edit" class="btn btn-primary">Edit</a>
    </div>
    </center>
  </div>
</div>

@endsection

resources/views/items/show.blade.php
@extends('welcome')

@section('content')

<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title">Article</h3>
    </div>
    <div class="card-header">
        <h3 class="card-title">Article</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <a href="/test-dompdf-2/{{$article->id}}" class="btn btn-sm btn-outline-success">Print PDF</a>
    <div class="card-body">
       
        <h1> {{$article->title}} </h1>
        <h3> Author : {{$article->author->name}} </h3>
        <h4> {{$article->detail_article}} </h4>
        
       
    </div>
    <a href="/article">Back</a>
            
                <!-- /.card-body -->
        <div class="card-footer">
            <h4> Comments </h4>
            @foreach ($comment as $comm)
            <div class="card card-primary mb-2">
                <div class="card-header">
                    <p>{{$comm->author->name}} comment: {{$comm->detail_comment}}</p>
                </div>    
            </div>    
            @endforeach

           
            <form role="form" action="{{route('comment.store',['article'=>$article->id])}}" method="post">
                @csrf
                @method('PUT')
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                <div class="card-body">
                    <div class="form-group">
                        <label for="comment">Write a Comment</label>
                        <input type="text" class="form-control" id="comment" name ="comment" value="{{old('comment', '')}}" placeholder="comment">
                        <button type="submit" class="btn btn-primary mt-2">Submit</button>
                    </div>       
                </div>      
            </form>
           
        </div>
    </form>
</div>

@endsection